name: Deploy document to GitHub Pages

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: pnpm --dir playground build

      - if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: playground/dist

  deploy:
    if: github.event_name == 'push'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
